stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - docker build -t speedtest-telegrambot .

deploy-job:
  stage: deploy
  script:
    - docker rm --force speedtest-telegrambot
    - docker run --name speedtest-telegrambot --restart unless-stopped -d speedtest-telegrambot
